name: Deploy Pipeline
run-name: Deploy:${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install pnpm
        run: npm install -g pnpm@9.15.0

      - name: Cache Dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js
        run: pnpm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: '/'

      - name: Debug Build Output Location
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of .next directory:"
          ls -la .next || echo ".next directory not found"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next/
          if-no-files-found: error

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next/

      - name: Debug Download Location
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of .next directory:"
          ls -la .next || echo ".next directory not found"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lost-no-more-fe
          directory: ${{ github.workspace }}/.next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
