name: Deploy Pipeline
run-name: Deploy:${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
      - name: Install pnpm
        run: npm install -g pnpm@9.15.0
      - name: Cache Dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Next.js
        run: pnpm run build
        env:
          NODE_ENV: production
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .next/ --project-name=lost-no-more-fe
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
